notarealfile.pdf: 
	pdflatex main.tex
	pdflatex main.tex
	bibtex main
	pdflatex main.tex
	bibtex main
	pdflatex main.tex
	

clean:
	rm -f *.pdf
	rm -f *.dvi
	rm -f *.toc
	rm -f *.aux
	rm -f *.bbl
	rm -f *.log
	rm -f *.blg
	rm -f *.bak
	rm -f *.out
	rm -f *.ps
	rm -f *.synctex.gz
